### ISSUE TITLE
Ajouter `make build` à la CI

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#59]
## Motivation

Cette commande est effectuée lors du déploiement du client. Si elle échoue, le déploiement échoue aussi, ce qui n'est pas souhaitable.

Actuellement on ne l'exécute pas sur la CI, et on ne l'exécute pas typiquement localement lors du dev non plus, ce qui fait qu'un problème peut passer et arriver jusqu'à `master`, puis péter lors du déploiement.

## Autre contexte

Exemple : je viens de déployer 915da674571edfa160eb87a51f045dbd99c0aa4d et d'obtenir un échec avec une liste d'erreurs de ce type :

```
13:57:46 [vite-plugin-svelte] /home/florimond/dev/prj-catalogue/catalogage-donnees/client/src/lib/footer/Footer.svelte:1:26 A11y: Redundant role 'contentinfo'
1: <footer class="fr-footer" role="contentinfo" id="footer">
```

Ainsi que :

```
> Using @sveltejs/adapter-node
> 404 /node_modules/@gouvfr/dsfr/dist/favicon/apple-touch-icon.png (linked from /)
    at file:///home/florimond/dev/prj-catalogue/catalogage-donnees/client/node_modules/@sveltejs/kit/dist/chunks/index5.js:409:11
    at visit (file:///home/florimond/dev/prj-catalogue/catalogage-donnees/client/node_modules/@sveltejs/kit/dist/chunks/index5.js:583:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
make: *** [Makefile:21: build] Error 1
```

**Comment by florimondmanca** [comment]
## Investigation

En fait c'est surtout l'erreur concernant les fichiers contenus dans le template HTML (favicon issus du DSFR) qui semblent poser problème.

Une fois que je les commente, j'obtiens d'autres erreurs, concernant les pages qui n'existent pas encore (il faut garder à l'esprit qu'au build, SvelteKit va se balader partout pour éventuellement faire du pré-rendu) :

```
> Using @sveltejs/adapter-node
> 404 /rechercher (linked from /)
```

Une fois ces `href` remplacés par par ex `href="#"`, le build réussit (exit code 0) malgré les avertissements d'accessibilité.

**Comment by florimondmanca** [comment]
@magopian J'ai ouvert la PR #60, je sèche un peu sur les liens vers les icônes depuis `@gouv/dsfr`. Je t'assigne cette issue
